package Model;

public class Reservation {

    public int reservation_id;
    public int user_id;
    public int number_guest;
    public long date_time; //it might String, we are not sure and ask Ted.

    public Reservation() {
    }
    // Posting a new reservation. reservation_id is generated by the database,
    // a constructor without reservation_id is needed.
    public Reservation(int user_id, int number_guest, int date_time) {
        this.user_id = user_id;
        this.number_guest = number_guest;
        this.date_time = date_time;
    }

    public Reservation(int reservation_id, int user_id, int number_guest, long date_time) {
        this.reservation_id = reservation_id;
        this.user_id = user_id;
        this.number_guest = number_guest;
        this.date_time = date_time;
    }

    public int getReservation_id() {
        return reservation_id;
    }

    public void setReservation_id(int reservation_id) {
        this.reservation_id = reservation_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setGuest_id(int user_id) {
        this.user_id = user_id;
    }

    public int getNumber_guest() {
        return number_guest;
    }

    public void setNumber_guest(int number_guest) {
        this.number_guest = number_guest;
    }
    public long getDate_time() {
        return date_time;
    }

    public void setDate_time(long date_time) {
        this.date_time = date_time;
    }


}
