package Model;

public class Reservation {

    public int reservation_id;
    public int user_id;
    public int number_guest;
    public String date_reservation; //we may convert the data type for this.

    public Reservation() {
    }
    // Posting a new reservation. reservation_id is generated by the database,
    // a constructor without reservation_id is needed.
    public Reservation(int user_id, int number_guest, String date_reservation) {
        this.user_id = user_id;
        this.number_guest = number_guest;
        this.date_reservation = date_reservation;
    }

    public Reservation(int reservation_id, int user_id, int number_guest, String date_reservation) {
        this.reservation_id = reservation_id;
        this.user_id = user_id;
        this.number_guest = number_guest;
        this.date_reservation = date_reservation;
    }

    public int getReservation_id() {
        return reservation_id;
    }

    public void setReservation_id(int reservation_id) {
        this.reservation_id = reservation_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public int getNumber_guest() {
        return number_guest;
    }

    public void setNumber_guest(int number_guest) {
        this.number_guest = number_guest;
    }
    public String getDate_reservation() {
        return date_reservation;
    }

    public void setDate_reservation(String date_reservatioin) {
        this.date_reservation = date_reservation;
    }


}
